import insomniaTextureLarge from '~/assets/insomnia-home.avif';
import insomniaTexturePlaceholder from '~/assets/insomnia-home.avif';
import insomniaTexture from '~/assets/insomnia-home.avif';
import riceLeafTexture from '~/assets/rice-leaf-home.jpg';
import seaweedTexture from '~/assets/seaweed-gan-home.png';
import pipelineTexture from '~/assets/spr-background.jpg';
import dashboardTexture from '~/assets/loki.jpg';
import { Footer } from '~/components/footer';
import { baseMeta } from '~/utils/meta';
import { Intro } from './intro';
import { Profile } from './profile';
import { ProjectSummary } from './project-summary';
import { useEffect, useRef, useState } from 'react';
import config from '~/config.json';
import styles from './home.module.css';

// Prefetch draco decoader wasm
export const links = () => {
  return [
    {
      rel: 'prefetch',
      href: '/draco/draco_wasm_wrapper.js',
      as: 'script',
      type: 'text/javascript',
      importance: 'low',
    },
    {
      rel: 'prefetch',
      href: '/draco/draco_decoder.wasm',
      as: 'fetch',
      type: 'application/wasm',
      importance: 'low',
    },
  ];
};

export const meta = () => {
  return baseMeta({
    title: 'AI Researcher + Developer',
    description: `Portfolio of ${config.name} — an AI researcher and developer based in Seoul, specializing in data automation, image processing, and machine learning.`,
  });
};

export const Home = () => {
  const [visibleSections, setVisibleSections] = useState([]);
  const [scrollIndicatorHidden, setScrollIndicatorHidden] = useState(false);
  const intro = useRef();
  const projectOne = useRef();
  const projectTwo = useRef();
  const projectThree = useRef();
  const projectFour = useRef();
  const projectFive = useRef();
  const details = useRef();

  useEffect(() => {
    const sections = [intro, projectOne, projectTwo, projectThree, projectFour, projectFive, details];

    const sectionObserver = new IntersectionObserver(
      (entries, observer) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            const section = entry.target;
            observer.unobserve(section);
            if (visibleSections.includes(section)) return;
            setVisibleSections(prevSections => [...prevSections, section]);
          }
        });
      },
      { rootMargin: '0px 0px -10% 0px', threshold: 0.1 }
    );

    const indicatorObserver = new IntersectionObserver(
      ([entry]) => {
        setScrollIndicatorHidden(!entry.isIntersecting);
      },
      { rootMargin: '-100% 0px 0px 0px' }
    );

    sections.forEach(section => {
      sectionObserver.observe(section.current);
    });

    indicatorObserver.observe(intro.current);

    return () => {
      sectionObserver.disconnect();
      indicatorObserver.disconnect();
    };
  }, [visibleSections]);

  return (
    <div className={styles.home}>
      <Intro
        id="intro"
        sectionRef={intro}
        scrollIndicatorHidden={scrollIndicatorHidden}
      />
      <ProjectSummary
        id="project-1"
        sectionRef={projectOne}
        visible={visibleSections.includes(projectOne.current)}
        index={1}
        title="Seaweed - GAN model"
        description="Generating images from source seaweed images"
        buttonText="View project"
        buttonLink="/projects/seaweed-gan"
        model={{
          type: 'laptop',
          alt: 'Sample seaweed image generated by the GAN model',
          textures: [
            {
              srcSet: `${seaweedTexture} 1280w, ${seaweedTexture} 2560w`,
              placeholder: seaweedTexture,
            },
          ],
        }}
      />
      <ProjectSummary
        id="project-2"
        alternate
        sectionRef={projectTwo}
        visible={visibleSections.includes(projectTwo.current)}
        index={2}
        title="Insomnia"
        description="Insomnia - Data Analysis and Automation project"
        buttonText="View project"
        buttonLink="/projects/insomnia"
        model={{
          type: 'laptop',
          alt: 'Sleep data analysis output from the Insomnia project',
          textures: [
            {
              srcSet: `${insomniaTexture} 375w, ${insomniaTextureLarge} 750w`,
              placeholder: insomniaTexturePlaceholder,
            },
          ],
        }}
      />

      <ProjectSummary
        id="project-3"
        sectionRef={projectThree}
        visible={visibleSections.includes(projectThree.current)}
        index={3}
        title="Image Classification"
        description="Rice Leaf Disease Classification"
        buttonText="View project"
        buttonLink="/projects/rice-leaf"
        model={{
          type: 'laptop',
          alt: 'Diseased rice leaf classified by the ResNet18 model',
          textures: [
            {
              srcSet: `${riceLeafTexture} 800w, ${riceLeafTexture} 1920w`,
              placeholder: riceLeafTexture,
            },
          ],
        }}
      />
      <ProjectSummary
        id="project-4"
        alternate
        sectionRef={projectFour}
        visible={visibleSections.includes(projectFour.current)}
        index={4}
        title="AIFORUS News Pipeline"
        description="Production AI news collection and tagging pipeline at Aiforus"
        buttonText="View project"
        buttonLink="/projects/aiforus-pipeline"
        model={{
          type: 'laptop',
          alt: 'AIFORUS news pipeline architecture',
          textures: [
            {
              srcSet: `${pipelineTexture} 1280w, ${pipelineTexture} 2560w`,
              placeholder: pipelineTexture,
            },
          ],
        }}
      />
      <ProjectSummary
        id="project-5"
        sectionRef={projectFive}
        visible={visibleSections.includes(projectFive.current)}
        index={5}
        title="AIFORUS Dashboard"
        description="React + Leaflet + Recharts dashboard for the AIFORUS pipeline"
        buttonText="View project"
        buttonLink="/projects/aiforus-dashboard"
        model={{
          type: 'laptop',
          alt: 'AIFORUS dashboard with map and trend charts',
          textures: [
            {
              srcSet: `${dashboardTexture} 1280w, ${dashboardTexture} 2560w`,
              placeholder: dashboardTexture,
            },
          ],
        }}
      />
      <Profile
        sectionRef={details}
        visible={visibleSections.includes(details.current)}
        id="details"
      />
      <Footer />
    </div>
  );
};
